language: python
python:
    - 2.7

virtualenv:
  system_site_packages: true

branches:
  only:
    - master

before_install:
  # Use miniconda and conda packages to speed up dependency setup (principally 
  # borrowed from https://gist.github.com/dan-blanchard/7045057
  # and https://github.com/Jorge-C/ordination/blob/master/.travis.yml
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran python-qt4
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Update conda itself
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Additional channel for pyqt4
  - conda config --add channels asmeurer
  # matplotlib needs a DISPLAY
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


install:
  - conda create --yes -n pelenv python=$TRAVIS_PYTHON_VERSION nose pip cython numpy scipy matplotlib qt pyqt sqlalchemy networkx
  - source activate pelenv
  - pip install munkres hungarian pyro4 brewer2mpl pyopengl coverage coveralls
  - python setup.py build --fcompiler=gfortran
  - python setup.py install
  - cp .coveragerc $HOME
  - pwd
  - sourcedir=$PWD
  # build the c++ tests
  - cd cpp_tests
  - cpp_test_dir=$PWD
  - ./get_gtest.sh
  - mkdir build && cd build
  - cmake ../source
  - make

script:
  # avoid running in the checkout directory so nose finds built modules..
  - cd $HOME
  - nosetests --with-coverage pele
  # do the c++ tests
  - $cpp_test_dir/build/test_main

after_success:
  # need to be in source directory to call coverage
  - cd $sourcedir # not sure if this is necessary
  - cp $HOME/.coverage .
  - coveralls
